spring.application.name=api-gateway
server.port=8080

jwt.secret=${JWT_SECRET}

# ----------------------------------------
# ROUTING - Auth (login) → arahkan ke user-service
# ----------------------------------------
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://user-service:1000
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

# ----------------------------------------
# ROUTING - User Service
# ----------------------------------------
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://user-service:1000
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/users/**

# ----------------------------------------
# ROUTING - Account Service
# ----------------------------------------
spring.cloud.gateway.server.webmvc.routes[2].id=account-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://account-service:2000
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/accounts/**

# ----------------------------------------
# ROUTING - Transaction Service
# ----------------------------------------
spring.cloud.gateway.server.webmvc.routes[3].id=transaction-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://transaction-service:3000
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/transactions/**

# ----------------------------------------
# ROUTING - Notification Service
# ----------------------------------------
spring.cloud.gateway.server.webmvc.routes[4].id=notification-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://notification-service:4000
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/notifications/**

# ----------------------------------------
# ACTUATOR
# ----------------------------------------
management.endpoints.web.exposure.include=health,info